In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"E:\pradnya's programming\Domains\DataAnalytics\DA_clgAss\marketing_campaign.csv",sep='\t',lineterminator='\n')

df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response\r
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [8]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
            2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [9]:
# missing value
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response\r              0
dtype: int64

In [10]:
df['Income'] = df['Income'].fillna(df['Income'].median())

In [ ]:
#converting categorical to numeric

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Creating an instance of OneHotEncoder
onehotencoder = OneHotEncoder()

# Fitting and transforming the 'Marital_Status' column
marital_status_encoded = onehotencoder.fit_transform(df[['Marital_Status']]).toarray()
marital_status_encoded

# # Creating a DataFrame with the encoded values
marital_status_df = pd.DataFrame(marital_status_encoded, columns=onehotencoder.get_feature_names_out(['Marital_Status']))
marital_status_df

# # Concatenating the new DataFrame with the original DataFrame
df = pd.concat([df, marital_status_df], axis=1)

# # Dropping the original 'Marital_Status' column
df.drop('Marital_Status', axis=1, inplace=True)

# df.head()

In [20]:
df.head()

,ID,Year_Birth,Education,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,Z_Revenue,Response\r,Marital_Status_Absurd,Marital_Status_Alone,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single,Marital_Status_Together,Marital_Status_Widow,Marital_Status_YOLO
0,5524,1957,Graduation,58138.0,0,0,04-09-2012,58,635,88,...,11,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2174,1954,Graduation,46344.0,1,1,08-03-2014,38,11,1,...,11,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,4141,1965,Graduation,71613.0,0,0,21-08-2013,26,426,49,...,11,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,6182,1984,Graduation,26646.0,1,0,10-02-2014,26,11,4,...,11,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5324,1981,PhD,58293.0,1,0,19-01-2014,94,173,43,...,11,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
# Fitting and transforming the 'education' column
Education_encoded = onehotencoder.fit_transform(df[['Education']]).toarray()
Education_encoded

# # Creating a DataFrame with the encoded values
Education_encoded_df = pd.DataFrame(Education_encoded, columns=onehotencoder.get_feature_names_out(['Education']))
Education_encoded_df

# # # Concatenating the new DataFrame with the original DataFrame
df = pd.concat([df, marital_status_df], axis=1)

# # # Dropping the original 'Marital_Status' column
df.drop('Education', axis=1, inplace=True)
# df.head()

In [29]:
df.head()

,ID,Year_Birth,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,...,Marital_Status_Widow,Marital_Status_YOLO,Marital_Status_Absurd,Marital_Status_Alone,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single,Marital_Status_Together,Marital_Status_Widow,Marital_Status_YOLO
0,5524,1957,58138.0,0,0,04-09-2012,58,635,88,546,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2174,1954,46344.0,1,1,08-03-2014,38,11,1,6,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,4141,1965,71613.0,0,0,21-08-2013,26,426,49,127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,6182,1984,26646.0,1,0,10-02-2014,26,11,4,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5324,1981,58293.0,1,0,19-01-2014,94,173,43,118,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
# outlier
def z_score(df):
    upper_limit = (df.mean()) + (3*df.std())
    lower_limit = df['salary'].mean()-3*df['salary'].std()
    print("upper limit:",upper_limit)
    print("lower limit:",lower_limit)
    # print(type(upper_limit))

In [ ]:
import pandas as pd
df = pd.read_csv(r"D:\\Downloads\\merged_fitness_data.csv")
df.

Index(['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance',
       'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories', 'SleepDate',
       'TotalSleepRecords', 'TotalMinutesAsleep', 'TotalTimeInBed'],
      dtype='object')